### ISSUE TITLE
`canRedeem` logic incorrectly assuming you can only redeem if winner, ignoring invalid case

### ISSUE THREAD

**Issue by greenlucid** [SwaprHQ/presagio#104]
Reality can return invalid. The reality proxy that generates the payouts handles this case:

https://gnosisscan.io/address/0xab16d643ba051c11962da645f74632d3130c81e2#code

<img width="675" alt="image" src="https://github.com/user-attachments/assets/1d98e068-f916-49d6-b5f5-80b7a26260ea">

The questions created with Kleros arbitrator, can be arbitrated according to this policy, which decides what Invalid means. Invalid is a valid case, so reality can and will return it.

https://cdn.kleros.link/ipfs/QmZM12kkguXFk2C94ykrKpambt4iUVKsVsxGxDEdLS68ws/omen-rules.pdf

Two components that allow the user to redeem (getting them from #103 PR branch):

https://github.com/SwaprHQ/presagio/blob/abd67565d92415c4b6d3bfe5048f797c2432f9d0/app/components/CardBet.tsx
https://github.com/SwaprHQ/presagio/blob/abd67565d92415c4b6d3bfe5048f797c2432f9d0/app/components/UserBets.tsx

Which ultimately use a few "entities" helpers, one of them leads us to the issue:

https://github.com/SwaprHQ/presagio/blob/abd67565d92415c4b6d3bfe5048f797c2432f9d0/entities/markets/marketCondition.ts#L17

`canRedeem` is tied to `isWinner` which is false. If the market is "invalid", all options will have the same payout, so if you have any shares at all, you can redeem.

**Comment by 0xNF21** [comment]
I am a user, and this prediction has been finalized as invalid, so I cannot recover my money through Presagio. Is there something we can do about it?

https://presagio.pages.dev/markets?id=0x888209942881afb58f1bf4f0575094ca7eed6022
