### ISSUE TITLE
USD amounts in sDAI not properly reflected

### ISSUE THREAD

**Issue by greenlucid** [SwaprHQ/presagio#109]
Whenever the frontend is to render an amount in USD when the collateral token is sDAI (such as volume, of bet amount), it will always display zero.

I cannot test this frontend because I'm lacking the env variables. But, looking around the code:

https://github.com/SwaprHQ/presagio/blob/d618e5030af9b70b562f963a68f694b9cf47bc2a/entities/markets/trade.ts#L29

https://github.com/SwaprHQ/presagio/blob/d618e5030af9b70b562f963a68f694b9cf47bc2a/app/components/CardMarket.tsx#L38

`usdVolume` and `collateralAmountUSD` come from the Omen subgraph.

I'm speculating a little bit, but I'm guessing the subgraph is just this one, without modification? It contains those fields.

https://github.com/protofire/omen-subgraph/blob/master/schema.graphql

**Comment by kongzii** [comment]
I think this is also the reason why I can't see my bets on market's page even if I have a bet on that market:

![Screenshot by Dropbox Capture](https://github.com/user-attachments/assets/4530584b-94f1-49b3-8fa8-d8e1bc16ab76)

`hasBetted` is based on USDSpent and I guess that's always 0 as well

https://github.com/kongzii/presagio/blob/b1c7cc723d53983446267dfcdbf4a029ed19abca/app/components/UserBets.tsx#L150
