### ISSUE TITLE
Invalid market state not considered in `My Bets`

### ISSUE THREAD

**Issue by kongzii** [SwaprHQ/presagio#126]
For example, this market https://presagio.pages.dev/markets?id=0x14d1c2c828ba13da17f1a38fb9b67ef7853ec711 is finalizing as Invalid.

Our rebel agent bet on `Yes` outcome because it was cheap (price <0.5), so after the market is resolved as invalid, he indeed will be profitable from this bet (because in the end, `Yes` token is worth 0.5 after market resolves as invalid).

However, in my bets section, it looks like the market doesn't have an answer yet and that he lost the whole investment:

![Screenshot by Dropbox Capture](https://github.com/user-attachments/assets/61d6decf-8564-4c60-8219-4e622d07a025)

**Comment by berteotti** [comment]
Hey @kongzii,  we have to show market status and answer in this cards. Thanks for reporting it!
