### ISSUE TITLE
Hardcoded outcomeIndex in UserBets redeem

### ISSUE THREAD

**Issue by greenlucid** [SwaprHQ/presagio#97]
https://github.com/SwaprHQ/presagio/blob/71b76b0d4fea7cfcb90ebe7e47a00845f205675a/app/components/UserBets.tsx#L134

causes this tx to fail sometimes, when called from the /markets page. compare to this one, the one that renders on /my-bets page, which works:
https://github.com/SwaprHQ/presagio/blob/71b76b0d4fea7cfcb90ebe7e47a00845f205675a/app/components/CardBet.tsx#L155

**Comment by Diogomartf** [comment]
Hi greenlucid,

Thanks for reporting an issue and doing a PR. I'll take a look into it.

**Comment by Diogomartf** [comment]
Yes this looks like a bug, thanks for reporting and doing a PR. Will review it soon.

**Comment by Diogomartf** [comment]
More context on the error, if we call it with the wrong outcome index

<img width="1335" alt="image" src="https://github.com/user-attachments/assets/3e5f973e-229e-41c7-8379-09f806c37075">
